name: Deploy Obsidian Notes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Clone Quartz repository
      run: git clone https://github.com/jackyzha0/quartz.git
      working-directory: ${{ github.workspace }}

    - name: Install Quartz dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/quartz

    - name: Create and build Obsidian notes
      run: |
        cd quartz
        npx quartz create
        npx quartz build
      working-directory: ${{ github.workspace }}/quartz

    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "/path/to/built/files"
        target: "/path/on/vps"
